name: dart_age_date_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

dependencies:
  clock: ^1.1.1
  dart_numerics: ^0.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  reusable_tools: ^1.0.16
  super_measurement: ^1.0.14

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^2.2.0
  test: ^1.24.0
